version: '3.3'

services:
  meili:
    container_name: 'eng-blogs-meili'
    image: getmeili/meilisearch
    volumes:
      - data.ms:/data.ms
    ports:
      - "7700:7700"
    networks:
      - engineering-blogs
  aggregator:
    container_name: 'eng-blogs-aggregator'
    depends_on:
      - meili
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    networks:
      - engineering-blogs
    volumes:
      - ./src:/var/eng-blogs/src/
      - ./vendor:/var/eng-blogs/vendor/
volumes:
  data.ms:
  src:
  vendor:
networks:
  engineering-blogs: